# Generated by Django 3.1.5 on 2021-01-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instituicao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Instituição'),
        ),
    ]
