# Generated by Django 3.1.5 on 2021-01-27 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210126_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data nascimento'),
        ),
    ]
