# Generated by Django 3.1.5 on 2021-01-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210126_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
    ]
