# Generated by Django 3.1.6 on 2021-02-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_delete_questoes'),
        ('base', '0014_auto_20210202_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aula_atual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='aulas.aulas'),
        ),
    ]
