# Generated by Django 3.1.6 on 2021-02-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210204_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aula_atual',
        ),
    ]
