# Generated by Django 3.1.6 on 2021-02-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_questoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questoes',
        ),
    ]
